import "./scripts/geral.js";
import "./scripts/aula.js";
import "./scripts/listagemCursos.js";
import "./scripts/listagemAulas.js";
import "./scripts/matriculas.js";
import "./scripts/meusCursosAluno.js";
import "./scripts/meusCursosProfessor.js";
import "./scripts/persistenciaJsonsCursos.js";
import "./estruturas/formCadastroCurso.js";
